extension Strings {
    // 英文
    static let enTable: [String: String] = [
        "add_book_failed": "Failed to add book: {error}",
        "api_test_output_placeholder": "Tap \"Start tests\" to run API tests...",
        "api_test_running": "Testing...",
        "api_test_start": "Start tests",
        "api_test_title": "ISBN API Test",
        "appTitle": "ISBN Book Manager",
        "author_optional": "Author (optional)",
        "bookList_search_hint": "Please enter title",
        "book_added": "Book added",
        "book_deleted": "Book deleted",
        "book_not_found": "No book information found",
        "book_saved": "Book saved",
        "books": "Books",
        "cancel": "Cancel",
        "cannot_find_book": "Unable to find book information",
        "cannot_find_isbn_ncl": "Unable to find book information. See: {url}",
        "clipboard_paste_tooltip": "Paste from clipboard",
        "delete": "Delete",
        "delete_action": "Delete",
        "delete_book_failed": "Failed to delete book: {error}",
        "delete_confirm_content": "Are you sure you want to delete this book?",
        "delete_confirm_title": "Delete confirmation",
        "discard": "Discard",
        "edit": "Edit",
        "edit_book": "Edit Book",
        "empty_hint": "Try a different filter or add a book",
        "error_prefix": "Error: {message}",
        "example_lexile_hint": "e.g.: 850",
        "filter_all": "All",
        "filter_no_books": "No books for this filter",
        "filter_read": "Read",
        "filter_reading": "Reading",
        "filter_unread": "Unread",
        "filter_wishlist": "Wishlist",
        "finance_title": "Finance Overview",
        "finance_total_earned": "Total earned",
        "finance_total_profit": "Total profit",
        "finance_total_spent": "Total spent",
        "free_limit_reached": "Free version limit of {limit} books reached. Unlock unlimited books to continue.",
        "isbn_already_exists": "ISBN already exists in database",
        "isbn_error_invalid_format": "Invalid ISBN format",
        "label_author_required": "Author *",
        "label_description": "Description",
        "label_lexile": "Lexile (Measure)",
        "label_publisher_required": "Publisher *",
        "label_purchase_price_required": "Purchase price (NT$) *",
        "label_sale_price": "Sale price (NT$)",
        "label_title_required": "Title *",
        "language_label": "Language: {value}",
        "language_section_title": "Language",
        "lexile_cancel": "Cancel",
        "lexile_clipboard_none": "No Lexile value detected in clipboard",
        "lexile_fill": "Fill",
        "lexile_label": "Lexile: {score}L",
        "lexile_load_failed": "Load failed: {error}",
        "lexile_manual_label": "Manual input",
        "lexile_manual_title": "Manual Lexile input",
        "lexile_need_title_author": "Please enter title and author before searching Lexile",
        "lexile_refilled": "Lexile filled: {value}L",
        "lexile_title": "Lexile Lookup",
        "load_books_failed": "Failed to load books: {error}",
        "manual_isbn_hint": "Enter 10 or 13 digit ISBN",
        "manual_isbn_label": "Manual ISBN",
        "manual_isbn_title": "Manual ISBN",
        "my_books_title": "My books",
        "new_book": "New Book",
        "no_enabled_sources": "No ISBN sources enabled, please enable sources in Settings",
        "no_results_text": "No results (or no usable ISBN)",
        "paywall_buy": "Unlock for {price}",
        "paywall_feature_once": "One-time purchase — no subscription",
        "paywall_feature_profit": "Full profit tracking and statistics, always free",
        "paywall_feature_unlimited": "Unlimited books in your library",
        "paywall_restore": "Restore Purchase",
        "paywall_subtitle": "The free version stores up to {limit} books. Unlock once, keep cataloging forever.",
        "paywall_title": "Unlock Unlimited Books",
        "paywall_unavailable": "Store unavailable",
        "paywall_unlocked": "Unlimited books unlocked",
        "performSearch": "Search",
        "photo_failed": "Photo failed: {error}",
        "photo_taken": "Photo captured",
        "pleaseFillRequiredFields": "Please fill all required fields",
        "please_enter_isbn": "Please enter ISBN",
        "please_enter_title": "Please enter title",
        "progress_finish": "Finished reading",
        "progress_none": "None",
        "progress_percent": "Progress",
        "progress_start": "Started reading",
        "progress_title": "Reading Progress",
        "tags_hint": "Tags (comma-separated)",
        "goals_done": "Finished {done} of {goal} this year",
        "goals_hint": "Goal",
        "goals_percent": "%.1f%%",
        "goals_streak_best": "Best streak: {best} days",
        "goals_streak_current": "Current streak: {current} days",
        "goals_title": "Reading Goals",
        "profit_calculation": "Profit calculation",
        "profit_label": "Profit",
        "provider_book_record_sale_failed": "Failed to record sale: {error}",
        "purchase_date_title": "Purchase Date",
        "query_failed_error": "Query failed: {error}",
        "refresh_tooltip": "Refresh",
        "sale_date_title": "Sale Date",
        "saveAndLeave": "Save and leave",
        "save_book_button": "Save Book",
        "save_failed": "Save failed",
        "scan_area_hint": "Place the book barcode in the scan area",
        "scan_not_isbn_ean": "Please scan an ISBN barcode; this is an EAN",
        "scan_subtitle": "Use camera to scan (supports 978/979)",
        "scan_title": "Scan ISBN",
        "search_button": "Search",
        "search_by_title_subtitle": "Enter title/author, search Google Books",
        "search_by_title_title": "Search by title",
        "search_failed": "Search failed: {error}",
        "searching_title": "Searching...",
        "set_sale_date_label": "Set sale date",
        "similar_title": "Similar books",
        "settings_bok_subtitle": "Taiwan's largest online bookstore",
        "settings_bok_title": "Books.com.tw",
        "settings_common_websites_title": "Common lookup websites",
        "settings_enabled_sources": "Enabled sources: {enabled} / {total}",
        "settings_eslite_subtitle": "Eslite online bookstore",
        "settings_eslite_title": "Eslite",
        "settings_google_subtitle": "Global books database",
        "settings_google_title": "Google Books",
        "settings_jike_subtitle": "Community-maintained Chinese book info (unstable)",
        "settings_jike_title": "Community Chinese API",
        "settings_loc_subtitle": "US Library of Congress catalog (free, no key)",
        "settings_loc_title": "Library of Congress",
        "settings_wikidata_subtitle": "Wikimedia open knowledge base (free, no key)",
        "settings_wikidata_title": "Wikidata",
        "settings_language_title": "App Language",
        "settings_manual_query_subtitle": "Manual book lookup",
        "settings_openlibrary_subtitle": "Free open bibliographic data",
        "settings_openlibrary_title": "Open Library",
        "settings_rate_subtitle": "Enjoying the app? Leave us a review",
        "settings_rate_title": "Rate this App",
        "sync_failed": "Sync failed",
        "sync_subtitle": "Sync your book library to iCloud",
        "sync_success": "Synced",
        "sync_title": "Sync iCloud",
        "settings_sources_explain": "The system will try enabled sources in order and fall back to the next if a source fails. All APIs are free third-party services and may vary in reliability.",
        "settings_sources_subtitle": "Toggle ISBN sources to try in order",
        "settings_keys_explain": "Optional. Google Books needs an API key to avoid the free daily quota; Jike requires a key to work. Add keys here to improve lookup results.",
        "settings_keys_title": "API Keys (optional)",
        "settings_key_placeholder": "API key",
        "settings_title": "Settings",
        "settings_tnla_subtitle": "Lookup Taiwan-published books",
        "settings_tnla_title": "Taiwan National Library ISBN",
        "settings_unlock_subtitle": "Free version: up to {limit} books",
        "settings_unlock_title": "Unlock Unlimited Books",
        "settings_wikipedia_subtitle": "Supplementary bibliographic data from Wikipedia",
        "settings_wikipedia_title": "Wikipedia",
        "source_label": "Source: {value}",
        "stat_completion_title": "Completion",
        "stat_overview_title": "Reading Overview",
        "stat_read": "Read",
        "stat_reading": "Reading",
        "stat_total_books": "Total books",
        "stat_unread": "Unread",
        "statistics": "Statistics",
        "statistics_tab_finance": "Finance Stats",
        "statistics_tab_reading": "Reading Stats",
        "statistics_title": "Statistics",
        "stats_reading_label": "Reading: {count} books",
        "stats_unread_label": "Unread: {count} books",
        "take_photo": "Take photo",
        "unfinishedSearchContent": "You have an unfinished search or input. Perform search, discard changes, or continue editing?",
        "unfinishedSearchTitle": "Unfinished search or changes",
        "unknown_author": "Unknown author",
        "unknown_publisher": "Unknown publisher",
        "unknown_title": "Unknown title",
        "unsavedChangesContent": "You have unsaved changes. Save before leaving?",
        "unsavedChangesTitle": "Unsaved changes",
        "update_book_failed": "Failed to update book: {error}",
    ]

    // 繁體中文
    static let zhHantTable: [String: String] = [
        "add_book_failed": "新增書籍失敗: {error}",
        "api_test_output_placeholder": "點擊「開始測試」執行 API 測試...",
        "api_test_running": "測試進行中...",
        "api_test_start": "開始測試",
        "api_test_title": "ISBN API 測試",
        "appTitle": "ISBN 書籍管理",
        "author_optional": "作者（可選）",
        "bookList_search_hint": "請輸入書名",
        "book_added": "已新增書籍",
        "book_deleted": "書籍已刪除",
        "book_not_found": "查無書籍資訊",
        "book_saved": "書籍已儲存",
        "books": "書籍",
        "cancel": "取消",
        "cannot_find_book": "無法查詢到書籍資訊",
        "cannot_find_isbn_ncl": "無法查詢到此 ISBN 的書籍資訊，可前往 NCL 查詢：{url}",
        "clipboard_paste_tooltip": "貼上回填",
        "delete": "刪除",
        "delete_action": "刪除",
        "delete_book_failed": "刪除書籍失敗: {error}",
        "delete_confirm_content": "確定要刪除此書籍嗎？",
        "delete_confirm_title": "刪除確認",
        "discard": "放棄變更",
        "edit": "編輯",
        "edit_book": "編輯書籍",
        "empty_hint": "換個篩選或新增一本試試看",
        "error_prefix": "錯誤: {message}",
        "example_lexile_hint": "例如：850",
        "filter_all": "全部",
        "filter_no_books": "這個篩選沒有書籍",
        "filter_read": "已讀",
        "filter_reading": "閱讀中",
        "filter_unread": "未讀",
        "filter_wishlist": "想讀",
        "finance_title": "金額統計",
        "finance_total_earned": "總收入",
        "finance_total_profit": "總利潤",
        "finance_total_spent": "總支出",
        "free_limit_reached": "已達免費版 {limit} 本上限，解鎖無限書籍即可繼續建檔。",
        "isbn_already_exists": "ISBN 已存在於資料庫",
        "isbn_error_invalid_format": "無效的 ISBN 格式",
        "label_author_required": "作者 *",
        "label_description": "描述",
        "label_lexile": "藍思值 (Lexile Measure)",
        "label_publisher_required": "出版社 *",
        "label_purchase_price_required": "購買價格 (元) *",
        "label_sale_price": "售出價格 (元)",
        "label_title_required": "書名 *",
        "language_label": "語言：{value}",
        "language_section_title": "語言",
        "lexile_cancel": "取消",
        "lexile_clipboard_none": "剪貼簿未偵測到 Lexile 值",
        "lexile_fill": "回填",
        "lexile_label": "Lexile: {score}L",
        "lexile_load_failed": "載入失敗: {error}",
        "lexile_manual_label": "手動輸入",
        "lexile_manual_title": "手動輸入 Lexile 值",
        "lexile_need_title_author": "請先填入書名與作者再查詢 Lexile",
        "lexile_refilled": "已回填 Lexile：{value}L",
        "lexile_title": "Lexile 查詢",
        "load_books_failed": "載入書籍失敗: {error}",
        "manual_isbn_hint": "請輸入 10 或 13 位 ISBN",
        "manual_isbn_label": "手動輸入 ISBN",
        "manual_isbn_title": "手動輸入 ISBN",
        "my_books_title": "我的書籍",
        "new_book": "新增書籍",
        "no_enabled_sources": "尚未啟用任何查詢來源，請到設定頁開啟來源",
        "no_results_text": "查無結果（或無可用 ISBN）",
        "paywall_buy": "以 {price} 解鎖",
        "paywall_feature_once": "一次性買斷，無訂閱",
        "paywall_feature_profit": "利潤追蹤與統計功能永久免費",
        "paywall_feature_unlimited": "書庫數量無上限",
        "paywall_restore": "恢復購買",
        "paywall_subtitle": "免費版最多可建檔 {limit} 本書。一次解鎖，永久使用。",
        "paywall_title": "解鎖無限書籍",
        "paywall_unavailable": "商店暫時無法使用",
        "paywall_unlocked": "已解鎖無限書籍",
        "performSearch": "執行查詢",
        "photo_failed": "拍照失敗: {error}",
        "photo_taken": "已拍攝書籍封面",
        "pleaseFillRequiredFields": "請填入所有必填欄位",
        "please_enter_isbn": "請輸入 ISBN",
        "please_enter_title": "請輸入書名",
        "progress_finish": "閱讀完成日期",
        "progress_none": "無",
        "progress_percent": "閱讀進度",
        "progress_start": "開始閱讀日期",
        "progress_title": "閱讀進度",
        "tags_hint": "標籤（以逗號分隔）",
        "goals_done": "今年已完成 {done} / {goal} 本",
        "goals_hint": "目標",
        "goals_percent": "%.1f%%",
        "goals_streak_best": "最佳連續：{best} 天",
        "goals_streak_current": "目前連續：{current} 天",
        "goals_title": "閱讀目標",
        "profit_calculation": "利潤計算",
        "profit_label": "利潤",
        "provider_book_record_sale_failed": "記錄售出失敗：{error}",
        "purchase_date_title": "購買日期",
        "query_failed_error": "查詢失敗: {error}",
        "refresh_tooltip": "重新整理",
        "sale_date_title": "售出日期",
        "saveAndLeave": "儲存並離開",
        "save_book_button": "保存書籍",
        "save_failed": "儲存失敗",
        "scan_area_hint": "將書籍條碼放在掃描區域",
        "scan_not_isbn_ean": "請掃描 ISBN 條碼，這個是 EAN",
        "scan_subtitle": "使用相機掃描條碼（支援 978/979）",
        "scan_title": "掃描 ISBN",
        "search_button": "查詢",
        "search_by_title_subtitle": "輸入書名/作者，用 Google Books 搜尋",
        "search_by_title_title": "以書名查詢",
        "search_failed": "查詢失敗: {error}",
        "searching_title": "查詢中...",
        "set_sale_date_label": "設定售出日期",
        "similar_title": "相似書籍",
        "settings_bok_subtitle": "台灣最大網路書店",
        "settings_bok_title": "博客來",
        "settings_common_websites_title": "常用查詢網頁",
        "settings_enabled_sources": "已啟用來源：{enabled} / {total}",
        "settings_eslite_subtitle": "誠品線上書店",
        "settings_eslite_title": "誠品書店",
        "settings_google_subtitle": "全球書籍資料庫",
        "settings_google_title": "Google Books",
        "settings_jike_subtitle": "社群維護的中文書資訊，穩定度較低，預設關閉。",
        "settings_jike_title": "中文第三方免費 API",
        "settings_loc_subtitle": "美國國會圖書館館藏（免費，不需 key）",
        "settings_loc_title": "Library of Congress",
        "settings_wikidata_subtitle": "維基開放知識庫（免費，不需 key）",
        "settings_wikidata_title": "Wikidata",
        "settings_language_title": "App 語言",
        "settings_manual_query_subtitle": "手動查詢書籍資訊",
        "settings_openlibrary_subtitle": "完全免費開放資料，補足封面與基本元資料。",
        "settings_openlibrary_title": "Open Library",
        "settings_rate_subtitle": "喜歡這個 App 嗎？留個評論支持我們",
        "settings_rate_title": "為 App 評分",
        "sync_failed": "同步失敗",
        "sync_subtitle": "將書庫同步到 iCloud",
        "sync_success": "已同步",
        "sync_title": "同步 iCloud",
        "settings_sources_explain": "系統會依照上列順序逐一查詢，失敗時自動換下一個來源。所有 API 均為免費第三方服務，穩定度可能會有所差異。",
        "settings_sources_subtitle": "可切換使用的 ISBN 查詢來源，依序嘗試",
        "settings_keys_explain": "選填。Google Books 需 API key 才能避開免費每日額度；Jike 需 key 才能使用。填入 key 可明顯改善查詢結果。",
        "settings_keys_title": "API Key（選填）",
        "settings_key_placeholder": "API key",
        "settings_title": "設定",
        "settings_tnla_subtitle": "查詢台灣出版書籍資訊",
        "settings_tnla_title": "台灣國家圖書館 ISBN",
        "settings_unlock_subtitle": "免費版最多 {limit} 本",
        "settings_unlock_title": "解鎖無限書籍",
        "settings_wikipedia_subtitle": "維基百科參考書籍資訊，補充文獻數據。",
        "settings_wikipedia_title": "Wikipedia",
        "source_label": "來源：{value}",
        "stat_completion_title": "閱讀完成度",
        "stat_overview_title": "閱讀進度",
        "stat_read": "已讀",
        "stat_reading": "閱讀中",
        "stat_total_books": "總書籍",
        "stat_unread": "未讀",
        "statistics": "統計",
        "statistics_tab_finance": "金額統計",
        "statistics_tab_reading": "閱讀統計",
        "statistics_title": "統計報告",
        "stats_reading_label": "閱讀中: {count} 本",
        "stats_unread_label": "未讀: {count} 本",
        "take_photo": "拍攝封面",
        "unfinishedSearchContent": "您有尚未完成的查詢或輸入，要執行查詢、放棄變更還是繼續編輯？",
        "unfinishedSearchTitle": "有未完成的查詢或變更",
        "unknown_author": "未知作者",
        "unknown_publisher": "未知出版社",
        "unknown_title": "未知標題",
        "unsavedChangesContent": "您有未儲存的變更，要儲存後離開嗎？",
        "unsavedChangesTitle": "有未儲存的變更",
        "update_book_failed": "更新書籍失敗: {error}",
    ]

    // 簡體中文
    static let zhHansTable: [String: String] = [
        "add_book_failed": "新增书籍失败: {error}",
        "api_test_output_placeholder": "点击「开始测试」执行 API 测试...",
        "api_test_running": "测试进行中...",
        "api_test_start": "开始测试",
        "api_test_title": "ISBN API 测试",
        "appTitle": "ISBN 书籍管理",
        "author_optional": "作者（可选）",
        "bookList_search_hint": "请输入书名",
        "book_added": "已新增书籍",
        "book_deleted": "书籍已删除",
        "book_not_found": "查无书籍信息",
        "book_saved": "书籍已保存",
        "books": "书籍",
        "cancel": "取消",
        "cannot_find_book": "无法查询到书籍信息",
        "cannot_find_isbn_ncl": "无法查询到此 ISBN 的书籍信息，可前往 NCL 查询：{url}",
        "clipboard_paste_tooltip": "贴上回填",
        "delete": "删除",
        "delete_action": "删除",
        "delete_book_failed": "删除书籍失败: {error}",
        "delete_confirm_content": "确定要删除此书籍吗？",
        "delete_confirm_title": "删除确认",
        "discard": "放弃更改",
        "edit": "编辑",
        "edit_book": "编辑书籍",
        "empty_hint": "换个筛选或新增一本试试看",
        "error_prefix": "错误: {message}",
        "example_lexile_hint": "例如：850",
        "filter_all": "全部",
        "filter_no_books": "这个筛选没有书籍",
        "filter_read": "已读",
        "filter_reading": "阅读中",
        "filter_unread": "未读",
        "filter_wishlist": "想读",
        "finance_title": "金额统计",
        "finance_total_earned": "总收入",
        "finance_total_profit": "总利润",
        "finance_total_spent": "总支出",
        "free_limit_reached": "已达免费版 {limit} 本上限，解锁无限书籍即可繼續建档。",
        "isbn_already_exists": "ISBN 已存在于数据库",
        "isbn_error_invalid_format": "无效的 ISBN 格式",
        "label_author_required": "作者 *",
        "label_description": "描述",
        "label_lexile": "蓝思值 (Lexile Measure)",
        "label_publisher_required": "出版社 *",
        "label_purchase_price_required": "购买价格 (元) *",
        "label_sale_price": "售价 (元)",
        "label_title_required": "书名 *",
        "language_label": "语言：{value}",
        "language_section_title": "语言",
        "lexile_cancel": "取消",
        "lexile_clipboard_none": "剪贴板未检测到 Lexile 值",
        "lexile_fill": "回填",
        "lexile_label": "Lexile: {score}L",
        "lexile_load_failed": "加载失败: {error}",
        "lexile_manual_label": "手动输入",
        "lexile_manual_title": "手动输入 Lexile 值",
        "lexile_need_title_author": "请先填入书名与作者再查询 Lexile",
        "lexile_refilled": "已回填 Lexile：{value}L",
        "lexile_title": "Lexile 查询",
        "load_books_failed": "加载书籍失败: {error}",
        "manual_isbn_hint": "请输入 10 或 13 位 ISBN",
        "manual_isbn_label": "手动输入 ISBN",
        "manual_isbn_title": "手动输入 ISBN",
        "my_books_title": "我的书籍",
        "new_book": "新增书籍",
        "no_enabled_sources": "尚未启用任何查询来源，请到设置页开启来源",
        "no_results_text": "查无结果（或无可用 ISBN）",
        "paywall_buy": "以 {price} 解锁",
        "paywall_feature_once": "一次性买断，无订阅",
        "paywall_feature_profit": "利润追踪与统计功能永久免费",
        "paywall_feature_unlimited": "书库数量无上限",
        "paywall_restore": "恢复购买",
        "paywall_subtitle": "免费版最多可建档 {limit} 本书。一次解锁，永久使用。",
        "paywall_title": "解锁无限书籍",
        "paywall_unavailable": "商店暂时无法使用",
        "paywall_unlocked": "已解锁无限书籍",
        "performSearch": "执行查询",
        "photo_failed": "拍照失败: {error}",
        "photo_taken": "已拍摄书籍封面",
        "pleaseFillRequiredFields": "请填写所有必填栏位",
        "please_enter_isbn": "请输入 ISBN",
        "please_enter_title": "请输入书名",
        "progress_finish": "阅读完成日期",
        "progress_none": "无",
        "progress_percent": "阅读进度",
        "progress_start": "开始阅读日期",
        "progress_title": "阅读进度",
        "tags_hint": "标签（以逗号分隔）",
        "goals_done": "今年已完成 {done} / {goal} 本",
        "goals_hint": "目标",
        "goals_percent": "%.1f%%",
        "goals_streak_best": "最佳连续：{best} 天",
        "goals_streak_current": "目前连续：{current} 天",
        "goals_title": "阅读目标",
        "profit_calculation": "利润计算",
        "profit_label": "利润",
        "provider_book_record_sale_failed": "记录售出失败：{error}",
        "purchase_date_title": "购买日期",
        "query_failed_error": "查询失败: {error}",
        "refresh_tooltip": "重新整理",
        "sale_date_title": "售出日期",
        "saveAndLeave": "保存并离开",
        "save_book_button": "保存书籍",
        "save_failed": "保存失败",
        "scan_area_hint": "将书籍条码放在扫描区域",
        "scan_not_isbn_ean": "请扫描 ISBN 条码，这个是 EAN",
        "scan_subtitle": "使用相机扫描条码（支持 978/979）",
        "scan_title": "扫描 ISBN",
        "search_button": "查询",
        "search_by_title_subtitle": "输入书名/作者，用 Google Books 搜寻",
        "search_by_title_title": "以书名查询",
        "search_failed": "查询失败: {error}",
        "searching_title": "查询中...",
        "set_sale_date_label": "設定售出日期",
        "similar_title": "相似书籍",
        "settings_bok_subtitle": "台湾最大网络书店",
        "settings_bok_title": "博客来",
        "settings_common_websites_title": "常用查询网页",
        "settings_enabled_sources": "已启用来源：{enabled} / {total}",
        "settings_eslite_subtitle": "诚品线上书店",
        "settings_eslite_title": "诚品书店",
        "settings_google_subtitle": "全球书籍数据库",
        "settings_google_title": "Google Books",
        "settings_jike_subtitle": "社群维护的中文书资讯，稳定度较低，预设关闭。",
        "settings_jike_title": "中文第三方免費 API",
        "settings_loc_subtitle": "美国国会图书馆馆藏（免费，不需 key）",
        "settings_loc_title": "Library of Congress",
        "settings_wikidata_subtitle": "维基开放知识库（免费，不需 key）",
        "settings_wikidata_title": "Wikidata",
        "settings_language_title": "App 语言",
        "settings_manual_query_subtitle": "手动查询书籍信息",
        "settings_openlibrary_subtitle": "完全免费开放资料，补充封面与基本元资料。",
        "settings_openlibrary_title": "Open Library",
        "settings_rate_subtitle": "喜欢这个 App 吗？留个评论支持我们",
        "settings_rate_title": "为 App 评分",
        "sync_failed": "同步失败",
        "sync_subtitle": "将书库同步到 iCloud",
        "sync_success": "已同步",
        "sync_title": "同步 iCloud",
        "settings_sources_explain": "系统会依照上列顺序逐一查询，失败时自动换下一个来源。所有 API 均为免费第三方服务，稳定度可能会有所差异。",
        "settings_sources_subtitle": "可切换使用的 ISBN 查询来源，依序尝试",
        "settings_keys_explain": "选填。Google Books 需要 API key 才能避开免费每日额度；Jike 需要 key 才能使用。填入 key 可明显改善查询结果。",
        "settings_keys_title": "API Key（选填）",
        "settings_key_placeholder": "API key",
        "settings_title": "设置",
        "settings_tnla_subtitle": "查询台湾出版书籍信息",
        "settings_tnla_title": "台湾国家图书馆 ISBN",
        "settings_unlock_subtitle": "免费版最多 {limit} 本",
        "settings_unlock_title": "解锁无限书籍",
        "settings_wikipedia_subtitle": "维基百科参考书籍资讯，补充文献数据。",
        "settings_wikipedia_title": "Wikipedia",
        "source_label": "来源：{value}",
        "stat_completion_title": "阅读完成度",
        "stat_overview_title": "阅读进度",
        "stat_read": "已读",
        "stat_reading": "阅读中",
        "stat_total_books": "总书籍",
        "stat_unread": "未读",
        "statistics": "统计",
        "statistics_tab_finance": "金额统计",
        "statistics_tab_reading": "阅读统计",
        "statistics_title": "统计报告",
        "stats_reading_label": "阅读中: {count} 本",
        "stats_unread_label": "未读: {count} 本",
        "take_photo": "拍摄封面",
        "unfinishedSearchContent": "您有尚未完成的查询或输入，要执行查询、放弃更改还是继续编辑？",
        "unfinishedSearchTitle": "有未完成的查询或更改",
        "unknown_author": "未知作者",
        "unknown_publisher": "未知出版社",
        "unknown_title": "未知标题",
        "unsavedChangesContent": "您有未保存的更改，要保存后离开吗？",
        "unsavedChangesTitle": "有未保存的更改",
        "update_book_failed": "更新书籍失败: {error}",
    ]
}
